#!/bin/bash

set -eu -o pipefail

usage() {
  cat <<EOF
Usage: $(basename "$0") command [tag]

Manage the containerised baton instance.

Commands:
  build  Build the container image
  start  Start the instance, if it isn't already (default)
  stop   Stop the instance

Note that the build command will be invoked automatically when trying to
start an instance that has yet to be built. An optional tag can be
supplied with all commands to use a specific image tag (defaults to
"hgi/baton").
EOF
}

# TODO
